const grid = [
  [
    {
      isSelected: false,
      hasBomb: false,
      id: 'A1',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'B1',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'C1',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'D1',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'E1',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'F1',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'G1',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'H1',
      spacesNearBomb: 0,
    },
  ],
  [
    {
      isSelected: false,
      hasBomb: false,
      id: 'A2',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'B2',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'C2',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'D2',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'E2',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'F2',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'G2',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'H2',
      spacesNearBomb: 0,
    },
  ],
  [
    {
      isSelected: false,
      hasBomb: false,
      id: 'A3',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'B3',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'C3',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'D3',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'E3',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'F3',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'G3',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'H3',
      spacesNearBomb: 0,
    },
  ],
  [
    {
      isSelected: false,
      hasBomb: false,
      id: 'A4',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'B4',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'C4',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'D4',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'E4',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'F4',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'G4',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'H4',
      spacesNearBomb: 0,
    },
  ],
  [
    {
      isSelected: false,
      hasBomb: false,
      id: 'A5',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'B5',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'C5',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'D5',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'E5',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'F5',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'G5',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'H5',
      spacesNearBomb: 0,
    },
  ],
  [
    {
      isSelected: false,
      hasBomb: false,
      id: 'A6',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'B6',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'C6',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'D6',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'E6',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'F6',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'G6',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'H6',
      spacesNearBomb: 0,
    },
  ],
  [
    {
      isSelected: false,
      hasBomb: false,
      id: 'A7',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'B7',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'C7',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'D7',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'E7',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'F7',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'G7',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'H7',
      spacesNearBomb: 0,
    },
  ],
  [
    {
      isSelected: false,
      hasBomb: false,
      id: 'A8',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'B8',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'C8',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'D8',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'E8',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'F8',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'G8',
      spacesNearBomb: 0,
    },
    {
      isSelected: false,
      hasBomb: false,
      id: 'H8',
      spacesNearBomb: 0,
    },
  ],
];

export default grid;
